packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@tanstack/react-query": ^5.84.1
  "@tanstack/react-query-devtools": ^5.84.1
  "@vanilla-extract/css": ^1.17.4
  "@vanilla-extract/dynamic": ^2.1.5
  "@vanilla-extract/recipes": ^0.5.7
  "@vanilla-extract/next-plugin": ^2.4.14
  "dayjs": ^1.11.18
  "next": 15.4.1
  "react": 19.1.0
  "react-dom": 19.1.0
  "react-error-boundary": ^6.0.0
  "react-hook-form": ^7.62.0
  "zod": ^4.0.14
  "@hookform/resolvers": ^5.2.1
  "zustand": ^5.0.8

  "ts-node": ^10.9.2
  "typescript": ^5.8.3
  "prettier": ^3.6.2
  "eslint-plugin-prettier": ^5.5.3
  "eslint-config-prettier": ^10.1.8
  "eslint-config-next": 15.4.1
  "eslint": ^9
  "@eslint/eslintrc": ^3
  "@types/node": ^20
  "@types/react": ^19
  "@types/react-dom": ^19

  "node-mocks-http": ^1.17.2
  "vitest": ^3.2.4
  "vite-tsconfig-paths": ^5.1.4
  "@vanilla-extract/vite-plugin": ^5.1.1
  "@vitejs/plugin-react": ^5.0.4
  "@testing-library/dom": ^10.4.1
  "@testing-library/jest-dom": ^6.8.0
  "@testing-library/react": ^16.3.0
  "@testing-library/user-event": ^14.6.1