import { EditorThemeClasses } from "lexical";
import * as s from "./editor.css";

export const lexicalTheme: EditorThemeClasses = {
  paragraph: "",
  quote: s.quote,
  code: s.code,
  codeHighlight: {
    atrule: s.token.attr,
    attr: s.token.attr,
    boolean: s.token.property,
    builtin: s.token.selector,
    cdata: s.token.comment,
    char: s.token.selector,
    class: s.token.function,
    "class-name": s.token.function,
    comment: s.token.comment,
    constant: s.token.property,
    deleted: s.token.property,
    doctype: s.token.comment,
    entity: s.token.operator,
    function: s.token.function,
    important: s.token.variable,
    inserted: s.token.selector,
    keyword: s.token.attr,
    namespace: s.token.variable,
    number: s.token.property,
    operator: s.token.operator,
    prolog: s.token.comment,
    property: s.token.property,
    punctuation: s.token.punctuation,
    regex: s.token.variable,
    selector: s.token.selector,
    string: s.token.selector,
    symbol: s.token.property,
    tag: s.token.property,
    url: s.token.operator,
    variable: s.token.variable,
  },
  link: s.link,
  list: {
    listitem: s.listItem,
    nested: { listitem: s.listItem },
    ul: s.ul,
    ol: s.ol,
  },
  heading: {
    h1: s.heading.h1,
    h2: s.heading.h2,
    h3: s.heading.h3,
  },
  text: {
    bold: s.text.bold,
    italic: s.text.italic,
    underline: s.text.underline,
    strikethrough: s.text.strikethrough,
    code: s.text.code,
    subscript: s.text.sub,
    superscript: s.text.sup,
  },
} as const;
